version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_db
    restart: always
    networks:
      - java-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  backend:
    container_name: backend
    image: rupesh1997/backend:1.0.0
    ports:
      - "8181:8181"
    restart: always
    networks:
      - java-network
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/api/v1.0.0/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  frontend:
    container_name: frontend
    image: rupesh1997/frontend:1.0.0
    ports:
      - "8082:80"
    restart: always
    networks:
      - java-network
    depends_on:
      - backend

volumes:
  mysql-data:

networks:
  java-network: