application:
  cors:
    origins: http://localhost:5173,http://localhost:8080,http://51.120.247.60:8080,http://51.120.247.60:8181,http://51.120.247.60:8082

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/movie_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    static-path-pattern: /uploads/** # Serve static files from /uploads/**
  servlet:
    multipart:
      enabled: true # Enable multipart file uploads
      file-size-threshold: 10MB # Threshold before writing to disk
      max-file-size: 50MB # Maximum size of a single file
      max-request-size: 100MB # Maximum size of the entire request
  web:
    resources:
      static-locations: file:${file.upload.directory}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

file:
  upload:
    directory: uploads